import "@/style/globals.css"
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://mizaru.my.id/fa-pro/css/all.min.css" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}
